package base

// PLEASE DO NOT EDIT THIS FILE, IT IS GENERATED AND WILL BE OVERWRITTEN:
// https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-contribute-code

func BaseTestsInit() <-chan interface{} {
	ch := make(chan interface{})
	go func() interface{} {
		defer close(ch)
		defer ReturnPanicError(ch)
		TestLanguageSpecific()
		TestConstants()
		TestAfterConstructor()
		TestExtend()
		TestDeepExtend()
		TestCryptography()
		TestBinaryToBase64()
		TestDatetime()
		TestDecimalToPrecision()
		TestCapitalize()
		TestNumberToString()
		TestPrecise()
		TestSafeMethods()
		TestSafeTicker()
		TestJson()
		TestSortBy()
		TestSum()
		TestUrlencodeBase64()
		TestOmit()
		TestGroupBy()
		TestIndexBy()
		TestFilterBy()
		TestHandleMethods()
		TestRemoveRepeatedElementsFromArray()
		TestParsePrecision()
		TestPrecisionFromString()
		TestExtractParams()
		TestArraysConcat()

		retRes674 := (<-TestSetMarketsFromExchange())
		PanicOnError(retRes674)
		TestEthMethods()
		TestKeysort()
		TestUnique()

		retRes714 := (<-TestSleep())
		PanicOnError(retRes714)
		TestIo()
		return nil
	}()
	return ch
}
